# config/model.yaml

data:
  bin_dir: datasets
  bin_file: mel_spectrograms.h5
  data_key: mel_spectrograms
  lazy_load: true
  raw_dir: datasets/gin
  max_samples: 100
  sample_percentage: null
  variable_length: true
  
audio:
  sample_rate: 22050
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  n_mels: 80
  fmin: 0
  fmax: 8000
  f0_min: 50
  f0_max: 600
  max_audio_length: 10.0

  model:
    # 10 seconds * 22050 Hz / 256 hop_length ≈ 861 frames
    time_frames: 864  # Rounded to a multiple of 32 for cleaner downsampling
    mel_bins: 80