data:
  bin_dir: datasets
  bin_file: mel_spectrograms.h5
  mel_key: mel_spectrogram # Key for target mel spectrograms 
  phoneme_key: phone_sequence # Key for input phoneme sequences
  duration_key: adjusted_durations # Key for input duration sequences
  f0_key: f0 # Key for input F0 sequences
  midi_pitch_key: midi_pitch_estimated # Key for estimated MIDI pitch
  lazy_load: true
  raw_dir: datasets/gin
  raw_audio_key: raw_audio # Key for the raw audio waveform
  # max_samples: 100 # Set to null or remove to use full dataset
  sample_percentage: null
  variable_length: true
  min_phones_in_lab: 5 # Minimum number of phone entries required in a .lab file to process it

audio:
  sample_rate: 22050
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  n_mels: 80
  fmin: 0
  fmax: 8000
  f0_min: 50
  f0_max: 600
  max_audio_length: 10.0

# Model specific parameters
model:
  name: ProgressiveSVS # Upstream model name
  mel_bins: 80        # Shared: Output dimension (should match audio.n_mels)
  vocab_size: null    # Shared: Will be dynamically set from data

  # --- ProgressiveSVS Specific Parameters ---
  # Embedding dimensions
  f0_embed_dim: 64
  phone_embed_dim: 256
  midi_embed_dim: 64
  unvoiced_embed_dim: 16 # Dimension for unvoiced flag embedding
  # Resolution scaling factors (relative to full mel_bins)
  low_res_scale: 4
  mid_res_scale: 2

  # Channel configurations for each stage
  low_res_channels: [256, 256, 128]
  mid_res_channels: [128, 128, 64]
  high_res_channels: [64, 64, 32] # Updated channel config

  # --- Multi-band Config ---
  num_bands_stage1: 2
  num_bands_stage2: 3
  band_processing_stage2: 'separate' # Options: 'separate', 'shared'
  num_bands_stage3: 4
  band_processing_stage3: 'separate'
  # --- End Multi-band Config ---

  # Initial training stage (1, 2, or 3)
  current_stage: 1

# Vocoder specific parameters
vocoder:
  name: HiFiGAN
  
  # HiFi-GAN specific parameters (using V1 defaults as a base)
  hifigan:
    upsample_rates: [8, 8, 2, 2] # Product must equal audio.hop_length (256)
    upsample_kernel_sizes: [16, 16, 4, 4]
    upsample_initial_channel: 512
    resblock_kernel_sizes: [3, 7, 11]
    resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
    f0_embed_dim: 64 # Only used if use_f0_conditioning is true
    discriminator_periods: [2, 3, 5, 7, 11]
    discriminator_use_spectral_norm: false # Set to true for spectral normalization
    lrelu_slope: 0.1 # LeakyReLU slope for Generator and Discriminators
  
  # Audio generation parameters (noise_scale removed, handled internally if needed)
  use_f0_conditioning: true # NEW: Enable F0 conditioning for the vocoder
  
  # For different chunk-based processing
  chunk_size_seconds: 2.5  # Process audio in chunks of this duration

# Training Configuration
train:
  batch_size: 16        # Adjust based on GPU memory
  unvoiced_weight: 0.5  # Weight for unvoiced frames in loss calculation
  epochs_per_stage:
    stage1: 150
    stage2: 120
    stage3: 100
  
  val_interval: 1       # Run validation every N epochs
  log_dir: logs         # Base directory for all logs
  tensorboard_log_dir: logs # Subdirectory for TensorBoard logs
  checkpoint_dir: logs/checkpoints # Subdirectory for model checkpoints
  num_workers: 4        # DataLoader workers
  log_spectrogram_every_n_val_steps: 5 # Log spectrogram comparison every N validation steps

  # --- Stage-Specific Learning Rates ---
  learning_rate_per_stage:
    stage1: 0.0005  # Example LR for stage 1
    stage2: 0.0007  # Example LR for stage 2
    stage3: 0.0009  # Example LR for stage 3
  # --- End Stage-Specific Learning Rates ---

  # --- Global Optimizer/Scheduler Params ---
  weight_decay: 0.0001    # Adam weight decay
  lr_factor: 0.5          # Factor by which the learning rate will be reduced (scheduler)
  lr_patience: 10         # Number of epochs with no improvement after which learning rate will be reduced (scheduler)
  gradient_clip_val: 0.5  # Gradient clipping value
  freeze_loaded_weights: false # Default: Freeze weights when loading from ckpt

  # log_interval defines log_every_n_steps in Trainer
  log_interval: 50        # Log training metrics every N steps

  # --- Vocoder (HiFi-GAN) Training Specific Params ---
  # Loss weights for Generator
  lambda_feature_match: 2.0 # Weight for Feature Matching Loss (L1 distance between discriminator feature maps)
  lambda_adversarial: 1.0   # Weight for Adversarial Loss (Generator's perspective)
  lambda_mel_gan: 45.0      # Weight for Mel Spectrogram Loss (L1 distance between target and generated mel)

  # Optimizer parameters (separate for Generator and Discriminator)
  generator_learning_rate: 0.0002
  discriminator_learning_rate: 0.0002
  generator_betas: [0.8, 0.99]       # AdamW betas for Generator
  discriminator_betas: [0.8, 0.99]   # AdamW betas for Discriminator
  generator_weight_decay: 0.0        # Weight decay for Generator optimizer
  discriminator_weight_decay: 0.0    # Weight decay for Discriminator optimizer

  # Scheduler parameters (Example: ExponentialLR)
  lr_scheduler_gamma: 0.999          # Gamma for ExponentialLR scheduler

  vocoder_max_epochs: 1000 # Maximum epochs for vocoder training (can adjust)
  
  # --- Vocoder Logging ---
  log_vocoder_audio_epoch_interval: 5 # Log audio every N validation epochs
  log_n_vocoder_audio_samples: 2      # Number of audio samples to log from validation batch
  log_vocoder_spectrograms: true      # Whether to log spectrogram comparison plots