data:
  bin_dir: datasets
  bin_file: mel_spectrograms.h5
  data_key: mel_spectrograms
  lazy_load: true
  raw_dir: datasets/raw
  max_samples: 100
  variable_length: true
  
audio:
  sample_rate: 22050
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  n_mels: 80
  fmin: 0
  fmax: 8000
  f0_min: 50
  f0_max: 600
  max_audio_length: 10.0

model:
  # Progressive dimensions
  time_frames: 864
  mel_bins: 80
  low_res_scale: 4  # Downscaling factor for first stage
  mid_res_scale: 2  # Downscaling factor for second stage
  
  # Feature dimensions
  f0_embed_dim: 64
  phone_embed_dim: 128
  midi_embed_dim: 32
  
  # Balanced Architecture Settings
  low_res_channels: [224, 144, 96, 48]                  # ~100K parameters
  mid_res_channels: [48, 64, 72, 80, 72, 64]           # Deepened to ~120K parameters
  high_res_channels: [80, 64, 56, 48, 32, 16, 1]        # ~120K parameters
  
  # Progressive training
  current_stage: 2
  stage_epochs: [100, 200, 400]

train:
  batch_size: 16
  num_epochs: 200
  learning_rate: 0.00075  # Adjusted for Stage 2 (0.75× of 0.001)
  weight_decay: 0.0001
  lr_scheduler: reduce_on_plateau
  lr_patience: 5
  lr_factor: 0.5
  save_dir: logs/progressive_svs
  freeze_earlier_stages: false  # Ensure Stage 1 isn't frozen during Stage 2 training