# config/model.yaml for Attention-Free SVS

data:
  bin_dir: datasets
  bin_file: mel_spectrograms.h5
  data_key: mel_spectrograms
  lazy_load: true
  raw_dir: datasets/gin
  max_samples: 10
  sample_percentage: null
  variable_length: true
  
  # SVS-specific data keys
  phone_key: phone_ids
  f0_key: f0
  duration_key: durations
  midi_key: midi_ids
  phone_vocab_size: 50
  midi_vocab_size: 128
  
audio:
  sample_rate: 22050
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  n_mels: 80
  fmin: 0
  fmax: 8000
  f0_min: 50
  f0_max: 600
  max_audio_length: 10.0

model:
  # Core architecture parameters
  time_frames: 864  # Support for 10 seconds of audio
  mel_bins: 80
  
  # Input processing modules
  phone_embed_dim: 64
  f0_embed_dim: 32
  duration_embed_dim: 16
  midi_embed_dim: 32
  
  # Dilated convolution backbone
  backbone_channels: 128
  num_paths: 3
  
  # Path 1 - Small dilation configuration
  path1_kernel_sizes: [3, 3, 3]
  path1_dilation_rates: [1, 2, 4]
  path1_channels: 48
  
  # Path 2 - Medium dilation configuration
  path2_kernel_sizes: [5, 5, 5]
  path2_dilation_rates: [1, 4, 8]
  path2_channels: 40
  
  # Path 3 - Large dilation configuration
  path3_kernel_sizes: [7, 7, 7]
  path3_dilation_rates: [1, 8, 16]
  path3_channels: 40
  
  # Feature mixing
  feature_mixing_kernel: 3
  use_depth_wise: true
  
  # Decoder configuration
  upsampling_factors: [2, 2]  # Total upsampling: 4x
  
  # Training features
  dropout_rate: 0.1
  variable_length_mode: true

train:
  batch_size: 4
  accumulate_grad_batches: 2
  num_epochs: 10
  learning_rate: 0.001
  weight_decay: 0.0001
  lr_scheduler: reduce_on_plateau
  lr_patience: 10
  lr_factor: 0.8
  validation_split: 0.1
  log_interval: 100
  save_dir: logs/attention_free_svs
  num_workers: 4
  pin_memory: true
  precision: '16-mixed'
  
validation:
  val_every_epoch: 5
  max_samples: 4
  log_spectrograms: true
  
inference:
  vocoder_path: pretrained/vocoder.pth  # Path to pretrained vocoder
  output_dir: outputs